dist: bionic
language: perl
os: [linux]
perl:
 - "5.28"
 - "5.26"
 - "5.24"
 - "5.22"
 - "5.20"
 - "5.18"
 - "5.16"
 - "5.14"
 - "blead"
 - "dev"
matrix:
  include:
    - perl: "5.16"
      env: COVERAGE=1
  allow_failures:
    - perl: blead
sudo: false
env:
  global:
    - PERL_CPANM_OPT="--notest --force --skip-satisified"
    - HARNESS_OPTIONS=j9
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpan-install EV Test::Pod Test::Pod::Coverage Test::Perl::Critic
git:
  depth: 3
